### ISSUE TITLE
HUD

### ISSUE THREAD

**Issue by 0xCCD** [crashmatt/MP_Aerodyn#1]
Hi i'm currently try to run your [HUD](https://github.com/crashmatt/MP_Aerodyn/tree/Thermik/Tools/HUD), unfortunately i have some issues

``` log
Working directory = /opt/MP_Aerodyn/Tools/HUD
Traceback (most recent call last):
  File "mav_pihud.py", line 488, in <module>
    mpstate.hud = HUD(master=True, update_queue=mpstate.update_queue, fullscreen=opts.fullscreen)
  File "/opt/MP_Aerodyn/Tools/HUD/HUD.py", line 107, in __init__
    self.init_graphics()
  File "/opt/MP_Aerodyn/Tools/HUD/HUD.py", line 169, in init_graphics
    self.DISPLAY = pi3d.Display.create(x=20, y=0, w=640, h=480, frames_per_second=self.fps, use_pygame=True, samples=4, fullscreen=self.fullscreen, no_frame=False)
TypeError: create() got an unexpected keyword argument 'fullscreen'
```

would be nice if you can help me to solve it 

Many thanks in advance

**Comment by crashmatt** [comment]
Wow! I never thought anyone else would ever look at this.

I am running a modified version of pi3d.  Fullscreen is a fix for doing
fullscreen with a linux/mesa setup rather than raspbian.  Paddy has been
merging some of my modifications so eventually I might get back to using
upstream.

https://github.com/crashmatt/pi3d

Please let me know what you are trying to do with it and I will do my best
to help.

/Matt

**Comment by 0xCCD** [comment]
i'm currently build a navio+ copter and i'm using the raspicam with u4vl for FPV over composite.
it starts as an overlay video on the main shell at DISPLAY: 0 and i try to use your HUD in the background of the video (currently there is just a shell)

I followed the instructions on the repository
https://github.com/crashmatt/pi3d

i guess that's the issue, how can i use your pi3d fork ? Clone the repository and extend $PYTHONPATH with the repository path ? I'm not so confident with python

**Comment by 0xCCD** [comment]
ok, i've found your [DOKU](https://docs.google.com/document/d/19DJErf3fOkTVeBRWvrK-WDfN0sqbgJiJ6qZa_EADLBI/edit) in a forum post and i've managed to install the pi3d, HUD is also starting, but unfortunately it is switching between the image below  

![shell](https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/320589/1981594/uDVf1v7HkVqhjLA/01_gem_paths.png)

and a black screen.

Probably i've missed something else as well

Many thanks in advance

**Comment by crashmatt** [comment]
The RPi is quite limited on graphics processor power.  I don't know if it
can handle video and HUD at the same time.  Since I wrote that document I
have been doing much work on reducing the processor overhead.  Some of
those changes have yet to make it into the repository.

It may be crashing somewhere.  Debugging on the RPi is horrible.  I do my
development on a linux machine under eclipse and then transfer it to the
RPi.  Do you have a linux PC?  It should also work under windows but I have
not tried it.

My repo is using a very specific version of mavlink with specific messages
for my aircraft.  This is likely to be a problem but should be possible to
fix.

You got my whole repository of junk along with the HUD.  I really should
organize it better. Ah well.

**Comment by 0xCCD** [comment]
I'm on the latest kubuntu version, and i've tried it also without video, but it still tells me this 'Queue full' msg. Pi is configured for sharing 128MB of memory with the graphic card.

As i understand, you have an updated version with less memory / cpu consumption, or is the current version up2date ?

**Comment by crashmatt** [comment]
I am using raspbian.  I don't know if that makes any difference.

The "queue full" message is caused when the mavlink interpreter has nowhere
left to put actions as an output from mavlink.  There is a headless thread
interpreting messages and putting HUD changes into a queue.  The pi3d loop
consumes the queue.  This means that the pi3d loop is not running and not
consuming messages.  You will need to debug to get to the cause.

The current version is mostly updated.  I have been changing the way the
graphics are drawn.  The old way is based on layers.  Layers prevent
re-drawing of all screen items at full refresh rate.  The new way uses
shaders to draw lots of the same thing very quickly.  I have already done
this for lines and boxes.  There is now a faster test drawing method that
completely removes the layers.  I have yet to implement this in the HUD.

/Matt
